### ISSUE TITLE
Load failure

### ISSUE THREAD

**Issue by w-p** [ilgizar/ilgizar-candlestick-panel#15]
Cloned today
Grafana 5.0.4
Fails with the error below when adding to a dashboard.
```
Plugin Error
Unexpected token , Instantiating http://0.0.0.0:3000/public/plugins/ilgizar-candlestick-panel/candlestick_ctrl.js Loading http://0.0.0.0:3000/public/plugins/ilgizar-candlestick-panel/module.js Loading plugins/ilgizar-candlestick-panel/module
```

**Comment by JamesGalt** [comment]
how did you installed it?

**Comment by w-p** [comment]
`git clone`, `npm install`, `grunt`, `unzip`, and `docker-compose up` with ...
```
version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - './dest/grafana/plugins:/var/lib/grafana/plugins'
      - './dest/grafana/grafana.ini:/etc/grafana/grafana.ini'
      - './dest/grafana/datasources:/etc/grafana/provisioning/datasources'
```
... where `./dest/grafana/plugins` contains ...
```
dest/grafana/plugins/
└── ilgizar-candlestick-panel
    ├── dist
    │   ├── candlestick_ctrl.js
    │   ├── candlestick_ctrl.js.map
    │   ├── colors.js
    │   ├── colors.js.map
    │   ├── img
    │   │   └── icn-candlestick-panel.svg
    │   ├── indicators_ctrl.js
    │   ├── indicators_ctrl.js.map
    │   ├── module.js
    │   ├── module.js.map
    │   ├── partials
    │   │   ├── editor.html
    │   │   ├── indicators.html
    │   │   └── module.html
    │   ├── plugin.json
    │   ├── README.md
    │   ├── rendering.js
    │   ├── rendering.js.map
    │   └── vendor
    │       ├── jquery_flot_axislabels.js
    │       └── jquery_flot_candlestick.js
    ├── Gruntfile.js
    ├── LICENSE
    ├── package.json
    ├── README.md
    └── src
        ├── candlestick_ctrl.js
        ├── colors.js
        ├── img
        │   └── icn-candlestick-panel.svg
        ├── indicators_ctrl.js
        ├── module.js
        ├── partials
        │   ├── editor.html
        │   ├── indicators.html
        │   └── module.html
        ├── plugin.json
        ├── rendering.js
        └── vendor
            ├── jquery_flot_axislabels.js
            └── jquery_flot_candlestick.js
```
